# Generated by Django 3.1.7 on 2021-03-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geofence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='coordinates',
            field=models.CharField(default='0', max_length=6382),
        ),
    ]
