# Generated by Django 3.1.7 on 2021-03-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('patient_name', models.CharField(max_length=200)),
                ('floor_name', models.CharField(max_length=200)),
                ('wifi_ssid', models.CharField(max_length=200)),
            ],
        ),
    ]
