# Generated by Django 3.1.7 on 2021-03-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('ssid', models.CharField(max_length=200)),
                ('rssi', models.CharField(max_length=200)),
                ('floor_name', models.CharField(max_length=200)),
                ('mp', models.CharField(max_length=200)),
            ],
        ),
    ]
