# Generated by Django 3.1.7 on 2021-03-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_tracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=200)),
                ('mp', models.CharField(max_length=200)),
                ('floor_name', models.CharField(max_length=200)),
                ('x', models.CharField(max_length=200)),
                ('y', models.CharField(max_length=200)),
            ],
        ),
    ]
